-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "bookingEndAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "bookingStartAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "coverImgUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "participatorNum" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Slot" ALTER COLUMN "availableParticipatorNum" SET DEFAULT 0;
